version: 2
project_name: sdexmon

builds:
  - main: .
    binary: sdexmon
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - "-s -w"
      - "-X main.appVersion={{.Version}}"
      - "-X main.gitCommit={{.ShortCommit}}"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

release:
  github:
    owner: sdexmon
    name: sdexmon
